//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavAnalyst {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NavAnalyst.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About NavAnalyst.
        /// </summary>
        internal static string AboutNavAnalyst {
            get {
                return ResourceManager.GetString("AboutNavAnalyst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About NavAnalyst.
        /// </summary>
        internal static string AboutNavAnalyst1 {
            get {
                return ResourceManager.GetString("AboutNavAnalyst1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All-In-View.
        /// </summary>
        internal static string AllInView {
            get {
                return ResourceManager.GetString("AllInView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessed.
        /// </summary>
        internal static string Assessed {
            get {
                return ResourceManager.GetString("Assessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az.
        /// </summary>
        internal static string Az {
            get {
                return ResourceManager.GetString("Az", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azimuth (degrees).
        /// </summary>
        internal static string AzimuthDegrees {
            get {
                return ResourceManager.GetString("AzimuthDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best-N.
        /// </summary>
        internal static string BestN {
            get {
                return ResourceManager.GetString("BestN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degrees.
        /// </summary>
        internal static string degrees {
            get {
                return ResourceManager.GetString("degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavAnalyst showcases some of the new features that are available from the Navigation utilities in DGL..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOP Analysis.
        /// </summary>
        internal static string DOPAnalysis {
            get {
                return ResourceManager.GetString("DOPAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOP Value.
        /// </summary>
        internal static string DOPValue {
            get {
                return ResourceManager.GetString("DOPValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDOP.
        /// </summary>
        internal static string EDOP {
            get {
                return ResourceManager.GetString("EDOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El.
        /// </summary>
        internal static string El {
            get {
                return ResourceManager.GetString("El", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation Angles.
        /// </summary>
        internal static string ElevationAngles {
            get {
                return ResourceManager.GetString("ElevationAngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation (degrees).
        /// </summary>
        internal static string ElevationDegrees {
            get {
                return ResourceManager.GetString("ElevationDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exists! Overwrite?.
        /// </summary>
        internal static string existsOverwrite {
            get {
                return ResourceManager.GetString("existsOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Exists.
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Mask Angle.
        /// </summary>
        internal static string FixedMaskAngle {
            get {
                return ResourceManager.GetString("FixedMaskAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDOP.
        /// </summary>
        internal static string GDOP {
            get {
                return ResourceManager.GetString("GDOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDOP.
        /// </summary>
        internal static string HDOP {
            get {
                return ResourceManager.GetString("HDOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meters.
        /// </summary>
        internal static string meters {
            get {
                return ResourceManager.GetString("meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Accuracy - Total System Error.
        /// </summary>
        internal static string NavigationAccuracy {
            get {
                return ResourceManager.GetString("NavigationAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NDOP.
        /// </summary>
        internal static string NDOP {
            get {
                return ResourceManager.GetString("NDOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Channels.
        /// </summary>
        internal static string NumberOfChannels {
            get {
                return ResourceManager.GetString("NumberOfChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDOP.
        /// </summary>
        internal static string PDOP {
            get {
                return ResourceManager.GetString("PDOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Error (m).
        /// </summary>
        internal static string PositionError {
            get {
                return ResourceManager.GetString("PositionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted.
        /// </summary>
        internal static string Predicted {
            get {
                return ResourceManager.GetString("Predicted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        internal static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Type.
        /// </summary>
        internal static string SolutionType {
            get {
                return ResourceManager.GetString("SolutionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDOP.
        /// </summary>
        internal static string TDOP {
            get {
                return ResourceManager.GetString("TDOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (GPST).
        /// </summary>
        internal static string TimeGPST {
            get {
                return ResourceManager.GetString("TimeGPST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (UTC).
        /// </summary>
        internal static string TimeUTC {
            get {
                return ResourceManager.GetString("TimeUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total System Error.
        /// </summary>
        internal static string TotalSystemError {
            get {
                return ResourceManager.GetString("TotalSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked.
        /// </summary>
        internal static string Tracked {
            get {
                return ResourceManager.GetString("Tracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VDOP.
        /// </summary>
        internal static string VDOP {
            get {
                return ResourceManager.GetString("VDOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
