using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompany("AGI, an Ansys Company")]
[assembly: AssemblyProduct("STK Components")]
[assembly: AssemblyCopyright("Copyright © 2007-2022 Analytical Graphics, Inc.")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("22.1.413.0")]
[assembly: AssemblyFileVersion("22.1.413.0")]
[assembly: NeutralResourcesLanguage("en-US")]

